version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: notes-kode-edu-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notesdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=notesdb
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
  
volumes:
  postgres_data:
