env: "local" #local, dev, prod
# For docker:
db_uri: "postgres://user:password@db:5432/notesdb?sslmode=disable"
# For local dev: 
# db_uri: "postgres://user:password@localhost:5432/notesdb?sslmode=disable"
token_ttl: 5h
http_server:
  address: "0.0.0.0:8080"
  timeout: 4s
  idle_timeout: 60s